# Generated by Django 3.1 on 2020-08-30 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='link',
            field=models.CharField(default='TBD', max_length=500),
        ),
        migrations.AddField(
            model_name='classes',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom'),
        ),
    ]
