# Generated by Django 3.1 on 2020-09-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayModels',
            new_name='Day',
        ),
    ]
