# Generated by Django 3.1 on 2020-09-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hours', '0002_auto_20200913_2302'),
        ('days', '0002_auto_20200913_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='days.day')),
                ('hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hours.hour')),
            ],
            options={
                'unique_together': {('hour', 'day')},
            },
        ),
    ]
