# Generated by Django 3.1 on 2020-08-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tutors', '0002_auto_20200604_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
