# Generated by Django 3.1 on 2020-09-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_hour', '0001_initial'),
        ('courses', '0002_auto_20200829_2204'),
        ('tutors', '0004_auto_20200829_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='tutor',
            name='hours',
            field=models.ManyToManyField(to='day_hour.DayHour'),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='course',
        ),
        migrations.AddField(
            model_name='tutor',
            name='course',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
