# Generated by Django 3.1 on 2020-08-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('event_assigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventassign',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
