# Generated by Django 3.1 on 2020-08-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='career',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='AAA333', max_length=10),
            preserve_default=False,
        ),
    ]
