# Generated by Django 3.1 on 2020-08-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriassessions',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
