# Generated by Django 3.1 on 2020-08-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias_sessions', '0002_tutoriassessions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriassessions',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
