# Generated by Django 3.1 on 2020-09-08 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200829_2204'),
        ('tutorias_sessions', '0003_tutoriassessions_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriassessions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='tutoriassessions',
            name='topic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
